image:
  file: .gitpod.dockerfile

vscode:
  extensions:
    - betterthantomorrow.calva

tasks:
  - name: Start REPL
    init: clojure -A:dev:build -P && (cd example && clojure -A:test -P)
    command: clojure -A:test
  - name: See Changes
    command: code CHANGELOG.md

github:
  prebuilds:
    main: true